export const SET_FOCUS_MODE = 'SET_FOCUS_MODE';
export const SET_SHOW_TOOLBOX = 'SET_SHOW_TOOLBOX';
export const SET_REMOVE_TOOL_STATE = 'SET_REMOVE_TOOL_STATE';
export const SET_SEARCH_ENGINE_IDX = 'SET_SEARCH_ENGINE_IDX';
export const GET_SEARCH_ENGINE_INDEX = 'SEARCH_ENGINE_INDEX';
export const SET_BACKGROUND_IMAGE = 'SET_BACKGROUND_IMAGE';
export const SET_SHOW_BEGINNER_TOUR = 'SET_SHOW_BEGINNER_TOUR';
export const SET_ADD_TOOL_DIALOG_VISIBLE = 'SET_ADD_TOOL_DIALOG_VISIBLE';
export const SET_ADD_CUSTOM_TOOL_DIALOG_VISIBLE =
  'SET_ADD_CUSTOM_TOOL_DIALOG_VISIBLE';
export const SET_SETTING_DIALOG_VISIBLE = 'SET_SETTING_DIALOG_VISIBLE';
export const SET_MANAGE_SEARCH_DIALOG_VISIBLE =
  'SET_MANAGE_SEARCH_DIALOG_VISIBLE';
export const SET_SELECTED_NOTE_ID = 'SET_SELECTED_NOTE_ID';
export const SET_BACKUP_AND_RESTORE_DIALOG_VISIBLE =
  'SET_BACKUP_AND_RESTORE_DIALOG_VISIBLE';

const controllers = 'controllers';
export const CONTROLLERS = {
  SET_FOCUS_MODE: `${controllers}/${SET_FOCUS_MODE}`,
  SET_SHOW_TOOLBOX: `${controllers}/${SET_SHOW_TOOLBOX}`,
  SET_REMOVE_TOOL_STATE: `${controllers}/${SET_REMOVE_TOOL_STATE}`,
  SET_SEARCH_ENGINE_IDX: `${controllers}/${SET_SEARCH_ENGINE_IDX}`,
  GET_SEARCH_ENGINE_INDEX: `${controllers}/${GET_SEARCH_ENGINE_INDEX}`,
  SET_BACKGROUND_IMAGE: `${controllers}/${SET_BACKGROUND_IMAGE}`,
  SET_SHOW_BEGINNER_TOUR: `${controllers}/${SET_SHOW_BEGINNER_TOUR}`,
  SET_ADD_TOOL_DIALOG_VISIBLE: `${controllers}/${SET_ADD_TOOL_DIALOG_VISIBLE}`,
  SET_ADD_CUSTOM_TOOL_DIALOG_VISIBLE: `${controllers}/${SET_ADD_CUSTOM_TOOL_DIALOG_VISIBLE}`,
  SET_SETTING_DIALOG_VISIBLE: `${controllers}/${SET_SETTING_DIALOG_VISIBLE}`,
  SET_MANAGE_SEARCH_DIALOG_VISIBLE: `${controllers}/${SET_MANAGE_SEARCH_DIALOG_VISIBLE}`,
  SET_SELECTED_NOTE_ID: `${controllers}/${SET_SELECTED_NOTE_ID}`,
  SET_BACKUP_AND_RESTORE_DIALOG_VISIBLE: `${controllers}/${SET_BACKUP_AND_RESTORE_DIALOG_VISIBLE}`
};

export const ADD_TOOL = 'ADD_TOOL';
export const REMOVE_TOOL = 'REMOVE_TOOL';
export const SET_TOOL_LIST = 'SET_TOOL_LIST';
export const SET_SEARCH_ENGINE_LIST = 'SET_SEARCH_ENGINE_LIST';
export const SAVE_USER_SETTINGS = 'SAVE_USER_SETTINGS';
export const SET_TODAY_BG = 'SET_TODAY_BG';
export const SET_SEARCH_RECORD = 'SET_SEARCH_RECORD';
export const CLEAR_SEAECH_RECORD = 'CLEAR_SEAECH_RECORD';
export const DELETE_SEARCH_RECORD = 'DELETE_SEARCH_RECORD';
export const ADD_NOTE = 'ADD_NOTE';
export const SET_NOTES = 'SET_NOTES';
export const DELETE_NOTE = 'DELETE_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const GET_NOTES_MAX_Z_INDEX = 'GET_NOTES_MAX_Z_INDEX';

const settings = 'settings';
export const SETTINGS = {
  ADD_TOOL: `${settings}/${ADD_TOOL}`,
  REMOVE_TOOL: `${settings}/${REMOVE_TOOL}`,
  SET_TOOL_LIST: `${settings}/${SET_TOOL_LIST}`,
  SET_SEARCH_ENGINE_LIST: `${settings}/${SET_SEARCH_ENGINE_LIST}`,
  SAVE_USER_SETTINGS: `${settings}/${SAVE_USER_SETTINGS}`,
  SET_TODAY_BG: `${settings}/${SET_TODAY_BG}`,
  SET_SEARCH_RECORD: `${settings}/${SET_SEARCH_RECORD}`,
  CLEAR_SEAECH_RECORD: `${settings}/${CLEAR_SEAECH_RECORD}`,
  DELETE_SEARCH_RECORD: `${settings}/${DELETE_SEARCH_RECORD}`,
  ADD_NOTE: `${settings}/${ADD_NOTE}`,
  SET_NOTES: `${settings}/${SET_NOTES}`,
  DELETE_NOTE: `${settings}/${DELETE_NOTE}`,
  UPDATE_NOTE: `${settings}/${UPDATE_NOTE}`,
  GET_NOTES_MAX_Z_INDEX: `${settings}/${GET_NOTES_MAX_Z_INDEX}`
};

export default {};
